# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bdd553541eb847b5a22e67344cf409ca"
name = "unlimited-options"
application_url = "https://unlimtited-options-recommendations.vercel.app/auth"
embedded = true

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://unlimtited-options-recommendations.vercel.app"
subpath = "unlimited-options"
prefix = "apps"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,write_draft_orders,read_draft_orders,write_inventory,read_inventory,read_orders,read_products,write_products,read_themes"

[auth]
redirect_urls = [
  "https://unlimtited-options-recommendations.vercel.app/auth"
]

extension_directories = ["./extensions"]
